FROM alpine:3.7

LABEL maintainer="Eagle  <422964429@qq.com>"


RUN \
     apk add --no-cache ca-certificates 'curl>7.61.0' && \
     echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf && \
     curl https://s3www-download.url > /usr/bin/s3www && \
     chmod +x /usr/bin/s3www

EXPOSE 8080

CMD ["s3www"]
